### ISSUE TITLE
Support install_github from devtools/remotes?

### ISSUE THREAD

**Issue by davidedelvento** [Oefenweb/ansible-r#21]
It would be great if this role would support `install_github` (and related) from [devtools](https://github.com/hadley/devtools) or from [remotes](https://github.com/r-lib/remotes) (which should be the same...)

Besides the convenience, some projects (e.g. [R for jupyter notebooks](https://github.com/IRkernel/IRkernel)) can only be installed this way.

Any plan or interest on supporting devtools/remotes?

**Comment by tersmitten** [comment]
Installation of packages from github.com is already supported, but I'm definitely interested in improving this and making more remotes available.

**Comment by davidedelvento** [comment]
Thanks for your answer.
Can you please elaborate some or point me to the documentation on how to install from github in the current version?

**Comment by tersmitten** [comment]
There's an example in the Readme. You need to specify an organization/repository and a type (github)

**Comment by brooklynbagel** [comment]
I'd be glad to work on improving it as well since I submitted the original PR. See the README [here](https://github.com/Oefenweb/ansible-r#advanced) and you'll find an example.

**Comment by tersmitten** [comment]
Also have a look at the `R-install-requirements` script that is included in this role. We use this script to install requirements for shiny-apps (from a file)

**Comment by maxolasersquad** [comment]
Something like this would be nice.
```yml
    r_packages:
      - name: dplyr
      - name: mypersonal/project
        type: customer
        uri: git@gitlab.mydomain.com
        credentials:
          pub_key: ~/.ssh/id_rsa.pub
          private_key: ~/.ssh/id_rsa
```

I'm not suggesting that this syntax is right, but something along these lines.
