### ISSUE TITLE
Default cran_mirror, public-key don't work

### ISSUE THREAD

**Issue by mhkhung** [Oefenweb/ansible-r#55]
These will..
```
- name: repository | add public key
  apt_key:
    id: FCAE2A0E115C3D8A
    keyserver: keyserver.ubuntu.com 
    state: present
  tags:
    - r-repository-public-key
- import_role:
    name: oefenweb.latest_r
  vars:
    r_install_dev: true
    r_cran_mirror: https://cloud.r-project.org
    r_version: "40"
    r_install:
      - r-recommended
 ```
